name: generators
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2
  collection: ^1.19.1
  meta: ^1.16.0
  # path: ^1.8.0

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  dart_style: ^2.3.7
  lints: ^3.0.0
  source_gen: ^1.5.0
  test: ^1.24.0
